import json
class GIS:
    """Handle GIS Functions"""
    
    # Methods
    def json_to_file(self, json_object):
        """convert geojson object to file

        Args:
            json_object (dict): geojson feature
        
        Return:
            file_path (str): path of the geojson file
        """
        file_path = "temp\\json\\output.json"
        with open(file_path, "w") as file:
            file.write( json.dumps(json_object) )
            
        return file_path
        




        
def main():
    json_object = {
            "type": "FeatureCollection",
            "features": [
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.338422,
                    24.158656
                    ]
                },
                "properties": {
                    "id": 323,
                    "checked": 'false',
                    "image": "/media/minipillar/upload/imgs/no_img.png",
                    "code": 'Null',
                    "manuf_serial_number": 'Null',
                    "miniPillar_type": 'Null',
                    "subtype_cd": 'Null',
                    "substation_number": 'Null',
                    "feeder_number": 'Null',
                    "circuits_number": 'Null',
                    "used_circuits_number": 'Null',
                    "subMiniPilar": 'Null',
                    "manuf_code": 'Null',
                    "manuf_year": 'Null',
                    "created_at": "2022-02-11T15:38:47.603115",
                    "user": "admin",
                    "updated_at": "2022-02-11T15:38:47.603115",
                    "updated_by": 'Null',
                    "entrance_obstacles": 'Null',
                    "equipment_grounding": 'Null',
                    "rusted_earthing_connection": 'Null',
                    "availability_noDang_signsMono": 'Null',
                    "substation_cleanliness": 'Null',
                    "equipment_level": 'Null',
                    "bumt_marks_sparks": 'Null',
                    "oxidation_corrosions": 'Null',
                    "dust_foreignDebris": 'Null',
                    "connectors_lugs": 'Null',
                    "bumt_heatingMarksOnCable": 'Null',
                    "urgent_issue": 'Null',
                    "urgent_issue_body": "'Null'",
                    "serious_issue": 'Null',
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": 'Null',
                    "rust_corrosion_deterioration": 'Null',
                    "paint_condition": 'Null',
                    "gaps_slots": 'Null',
                    "locks_hinges": 'Null',
                    "latching_mechanism": 'Null',
                    "cracks_damages": 'Null',
                    "gaps_unblockCableEntry": 'Null',
                    "galvanization_bolts_nuts_screws": 'Null',
                    "grounding_bounding": 'Null',
                    "access_obstructions": 'Null',
                    "numbering_dangerSigns_monogram": 'Null',
                    "maintenance_completed": 'Null',
                    "minorRepair_made": 'Null',
                    "latitude": 24.158656117544496,
                    "longitude": 47.3384217130019,
                    "last_check_at": "2022-02-11T15:38:47.603115",
                    "checked_by": 'Null',
                    "device": 'Null',
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.338556,
                    24.158705
                    ]
                },
                "properties": {
                    "id": 324,
                    "checked": 'false',
                    "image": "/media/minipillar/upload/imgs/no_img.png",
                    "code": 'Null',
                    "manuf_serial_number": 'Null',
                    "miniPillar_type": 'Null',
                    "subtype_cd": 'Null',
                    "substation_number": 'Null',
                    "feeder_number": 'Null',
                    "circuits_number": 'Null',
                    "used_circuits_number": 'Null',
                    "subMiniPilar": 'Null',
                    "manuf_code": 'Null',
                    "manuf_year": 'Null',
                    "created_at": "2022-02-11T15:38:47.613103",
                    "user": "admin",
                    "updated_at": "2022-02-11T15:38:47.613103",
                    "updated_by": 'Null',
                    "entrance_obstacles": 'Null',
                    "equipment_grounding": 'Null',
                    "rusted_earthing_connection": 'Null',
                    "availability_noDang_signsMono": 'Null',
                    "substation_cleanliness": 'Null',
                    "equipment_level": 'Null',
                    "bumt_marks_sparks": 'Null',
                    "oxidation_corrosions": 'Null',
                    "dust_foreignDebris": 'Null',
                    "connectors_lugs": 'Null',
                    "bumt_heatingMarksOnCable": 'Null',
                    "urgent_issue": 'Null',
                    "urgent_issue_body": "'Null'",
                    "serious_issue": 'Null',
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": 'Null',
                    "rust_corrosion_deterioration": 'Null',
                    "paint_condition": 'Null',
                    "gaps_slots": 'Null',
                    "locks_hinges": 'Null',
                    "latching_mechanism": 'Null',
                    "cracks_damages": 'Null',
                    "gaps_unblockCableEntry": 'Null',
                    "galvanization_bolts_nuts_screws": 'Null',
                    "grounding_bounding": 'Null',
                    "access_obstructions": 'Null',
                    "numbering_dangerSigns_monogram": 'Null',
                    "maintenance_completed": 'Null',
                    "minorRepair_made": 'Null',
                    "latitude": 24.158705296034977,
                    "longitude": 47.338556460108585,
                    "last_check_at": "2022-02-11T15:38:47.613103",
                    "checked_by": 'Null',
                    "device": 'Null',
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.338278,
                    24.156443
                    ]
                },
                "properties": {
                    "id": 327,
                    "checked": 'false',
                    "image": "/media/minipillar/upload/imgs/no_img.png",
                    "code": 'Null',
                    "manuf_serial_number": 'Null',
                    "miniPillar_type": 'Null',
                    "subtype_cd": 'Null',
                    "substation_number": 'Null',
                    "feeder_number": 'Null',
                    "circuits_number": 'Null',
                    "used_circuits_number": 'Null',
                    "subMiniPilar": 'Null',
                    "manuf_code": 'Null',
                    "manuf_year": 'Null',
                    "created_at": "2022-02-11T15:38:47.640934",
                    "user": "admin",
                    "updated_at": "2022-02-11T15:38:47.640934",
                    "updated_by": 'Null',
                    "entrance_obstacles": 'Null',
                    "equipment_grounding": 'Null',
                    "rusted_earthing_connection": 'Null',
                    "availability_noDang_signsMono": 'Null',
                    "substation_cleanliness": 'Null',
                    "equipment_level": 'Null',
                    "bumt_marks_sparks": 'Null',
                    "oxidation_corrosions": 'Null',
                    "dust_foreignDebris": 'Null',
                    "connectors_lugs": 'Null',
                    "bumt_heatingMarksOnCable": 'Null',
                    "urgent_issue": 'Null',
                    "urgent_issue_body": "'Null'",
                    "serious_issue": 'Null',
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": 'Null',
                    "rust_corrosion_deterioration": 'Null',
                    "paint_condition": 'Null',
                    "gaps_slots": 'Null',
                    "locks_hinges": 'Null',
                    "latching_mechanism": 'Null',
                    "cracks_damages": 'Null',
                    "gaps_unblockCableEntry": 'Null',
                    "galvanization_bolts_nuts_screws": 'Null',
                    "grounding_bounding": 'Null',
                    "access_obstructions": 'Null',
                    "numbering_dangerSigns_monogram": 'Null',
                    "maintenance_completed": 'Null',
                    "minorRepair_made": 'Null',
                    "latitude": 24.156443078434023,
                    "longitude": 47.33827798187797,
                    "last_check_at": "2022-02-11T15:38:47.640934",
                    "checked_by": 'Null',
                    "device": 'Null',
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.338404,
                    24.156509
                    ]
                },
                "properties": {
                    "id": 328,
                    "checked": 'false',
                    "image": "/media/minipillar/upload/imgs/no_img.png",
                    "code": 'Null',
                    "manuf_serial_number": 'Null',
                    "miniPillar_type": 'Null',
                    "subtype_cd": 'Null',
                    "substation_number": 'Null',
                    "feeder_number": 'Null',
                    "circuits_number": 'Null',
                    "used_circuits_number": 'Null',
                    "subMiniPilar": 'Null',
                    "manuf_code": 'Null',
                    "manuf_year": 'Null',
                    "created_at": "2022-02-11T15:38:47.647932",
                    "user": "admin",
                    "updated_at": "2022-02-11T15:38:47.647932",
                    "updated_by": 'Null',
                    "entrance_obstacles": 'Null',
                    "equipment_grounding": 'Null',
                    "rusted_earthing_connection": 'Null',
                    "availability_noDang_signsMono": 'Null',
                    "substation_cleanliness": 'Null',
                    "equipment_level": 'Null',
                    "bumt_marks_sparks": 'Null',
                    "oxidation_corrosions": 'Null',
                    "dust_foreignDebris": 'Null',
                    "connectors_lugs": 'Null',
                    "bumt_heatingMarksOnCable": 'Null',
                    "urgent_issue": 'Null',
                    "urgent_issue_body": "'Null'",
                    "serious_issue": 'Null',
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": 'Null',
                    "rust_corrosion_deterioration": 'Null',
                    "paint_condition": 'Null',
                    "gaps_slots": 'Null',
                    "locks_hinges": 'Null',
                    "latching_mechanism": 'Null',
                    "cracks_damages": 'Null',
                    "gaps_unblockCableEntry": 'Null',
                    "galvanization_bolts_nuts_screws": 'Null',
                    "grounding_bounding": 'Null',
                    "access_obstructions": 'Null',
                    "numbering_dangerSigns_monogram": 'Null',
                    "maintenance_completed": 'Null',
                    "minorRepair_made": 'Null',
                    "latitude": 24.15650865088177,
                    "longitude": 47.33840374668751,
                    "last_check_at": "2022-02-11T15:38:47.647932",
                    "checked_by": 'Null',
                    "device": 'Null',
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.333741,
                    24.152812
                    ]
                },
                "properties": {
                    "id": 319,
                    "checked": 'true',
                    "image": "/media/minipillar/upload/imgs/IMG_1644586813149.jpg",
                    "code": "esam",
                    "manuf_serial_number": "mohamed",
                    "miniPillar_type": 'Null',
                    "subtype_cd": "123",
                    "substation_number": "456",
                    "feeder_number": "258",
                    "circuits_number": "123",
                    "used_circuits_number": "147",
                    "subMiniPilar": 'Null',
                    "manuf_code": "eas",
                    "manuf_year": "moh",
                    "created_at": "2022-02-11T15:38:47.568130",
                    "user": "admin",
                    "updated_at": "2022-02-11T15:40:41.647241",
                    "updated_by": 'Null',
                    "entrance_obstacles": "'true'",
                    "equipment_grounding": "'true'",
                    "rusted_earthing_connection": "'true'",
                    "availability_noDang_signsMono": "'true'",
                    "substation_cleanliness": "'true'",
                    "equipment_level": "'false'",
                    "bumt_marks_sparks": "'false'",
                    "oxidation_corrosions": "'false'",
                    "dust_foreignDebris": "'true'",
                    "connectors_lugs": "'true'",
                    "bumt_heatingMarksOnCable": "'true'",
                    "urgent_issue": "'true'",
                    "urgent_issue_body": "'Null'",
                    "serious_issue": "'true'",
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": "10 - 20",
                    "rust_corrosion_deterioration": "20 - 40",
                    "paint_condition": "10 - 20",
                    "gaps_slots": "20 - 40",
                    "locks_hinges": "> 40",
                    "latching_mechanism": "10 - 20",
                    "cracks_damages": "10 - 20",
                    "gaps_unblockCableEntry": "20 - 40",
                    "galvanization_bolts_nuts_screws": "10 - 20",
                    "grounding_bounding": 'Null',
                    "access_obstructions": "20 - 40",
                    "numbering_dangerSigns_monogram": "10 - 20",
                    "maintenance_completed": "10 - 20",
                    "minorRepair_made": 'Null',
                    "latitude": 24.15281197235953,
                    "longitude": 47.333741490144234,
                    "last_check_at": "2022-02-11T15:40:41.647241",
                    "checked_by": "string",
                    "device": 5,
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.340021,
                    24.157771
                    ]
                },
                "properties": {
                    "id": 318,
                    "checked": 'true',
                    "image": "/media/minipillar/upload/imgs/IMG_1644596395619.jpg",
                    "code": "ali",
                    "manuf_serial_number": "Mohammed ",
                    "miniPillar_type": 'Null',
                    "subtype_cd": "ok",
                    "substation_number": "12345",
                    "feeder_number": "2345",
                    "circuits_number": "3456",
                    "used_circuits_number": "5648",
                    "subMiniPilar": 'Null',
                    "manuf_code": "esam",
                    "manuf_year": "sasa",
                    "created_at": "2022-02-11T15:38:45.490703",
                    "user": "admin",
                    "updated_at": "2022-02-11T18:20:22.145596",
                    "updated_by": 'Null',
                    "entrance_obstacles": "'true'",
                    "equipment_grounding": "'true'",
                    "rusted_earthing_connection": "'true'",
                    "availability_noDang_signsMono": "'false'",
                    "substation_cleanliness": "'false'",
                    "equipment_level": "'false'",
                    "bumt_marks_sparks": "'false'",
                    "oxidation_corrosions": "'true'",
                    "dust_foreignDebris": "'true'",
                    "connectors_lugs": "'true'",
                    "bumt_heatingMarksOnCable": "'true'",
                    "urgent_issue": "'true'",
                    "urgent_issue_body": "'Null'",
                    "serious_issue": "'true'",
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": "10 - 20",
                    "rust_corrosion_deterioration": "20 - 40",
                    "paint_condition": "> 40",
                    "gaps_slots": "10 - 20",
                    "locks_hinges": "20 - 40",
                    "latching_mechanism": "> 40",
                    "cracks_damages": "10 - 20",
                    "gaps_unblockCableEntry": "20 - 40",
                    "galvanization_bolts_nuts_screws": "10 - 20",
                    "grounding_bounding": 'Null',
                    "access_obstructions": "20 - 40",
                    "numbering_dangerSigns_monogram": "> 40",
                    "maintenance_completed": "10 - 20",
                    "minorRepair_made": 'Null',
                    "latitude": 24.157770906967517,
                    "longitude": 47.340020713404606,
                    "last_check_at": "2022-02-11T18:20:22.146584",
                    "checked_by": "string",
                    "device": 5,
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.335098,
                    24.155664
                    ]
                },
                "properties": {
                    "id": 320,
                    "checked": 'true',
                    "image": "/media/minipillar/upload/imgs/IMG_1644596551385.jpg",
                    "code": "123",
                    "manuf_serial_number": "osam",
                    "miniPillar_type": 'Null',
                    "subtype_cd": "mohamed",
                    "substation_number": "2345",
                    "feeder_number": "1234",
                    "circuits_number": "8524",
                    "used_circuits_number": "35478",
                    "subMiniPilar": 'Null',
                    "manuf_code": "hello",
                    "manuf_year": "welcome ",
                    "created_at": "2022-02-11T15:38:47.577128",
                    "user": "admin",
                    "updated_at": "2022-02-11T18:22:57.647056",
                    "updated_by": 'Null',
                    "entrance_obstacles": "'true'",
                    "equipment_grounding": "'true'",
                    "rusted_earthing_connection": "'false'",
                    "availability_noDang_signsMono": "'false'",
                    "substation_cleanliness": "'false'",
                    "equipment_level": "'true'",
                    "bumt_marks_sparks": "'true'",
                    "oxidation_corrosions": "'true'",
                    "dust_foreignDebris": "'false'",
                    "connectors_lugs": "'false'",
                    "bumt_heatingMarksOnCable": "'false'",
                    "urgent_issue": "'false'",
                    "urgent_issue_body": "'Null'",
                    "serious_issue": "'false'",
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": "20 - 40",
                    "rust_corrosion_deterioration": "10 - 20",
                    "paint_condition": "> 40",
                    "gaps_slots": "20 - 40",
                    "locks_hinges": "10 - 20",
                    "latching_mechanism": "20 - 40",
                    "cracks_damages": "> 40",
                    "gaps_unblockCableEntry": "10 - 20",
                    "galvanization_bolts_nuts_screws": "20 - 40",
                    "grounding_bounding": 'Null',
                    "access_obstructions": "> 40",
                    "numbering_dangerSigns_monogram": "10 - 20",
                    "maintenance_completed": "20 - 40",
                    "minorRepair_made": 'Null',
                    "latitude": 24.155664408186446,
                    "longitude": 47.33509794587083,
                    "last_check_at": "2022-02-11T18:22:57.647056",
                    "checked_by": "string",
                    "device": 5,
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.331145,
                    24.153976
                    ]
                },
                "properties": {
                    "id": 321,
                    "checked": 'true',
                    "image": "/media/minipillar/upload/imgs/IMG_1644598683544.jpg",
                    "code": "sama",
                    "manuf_serial_number": "Mohammed ",
                    "miniPillar_type": 'Null',
                    "subtype_cd": "123",
                    "substation_number": "147",
                    "feeder_number": "1312",
                    "circuits_number": "1712",
                    "used_circuits_number": "258",
                    "subMiniPilar": 'Null',
                    "manuf_code": "was",
                    "manuf_year": "sae",
                    "created_at": "2022-02-11T15:38:47.585120",
                    "user": "admin",
                    "updated_at": "2022-02-11T18:58:34.750957",
                    "updated_by": 'Null',
                    "entrance_obstacles": "'true'",
                    "equipment_grounding": "'true'",
                    "rusted_earthing_connection": "'true'",
                    "availability_noDang_signsMono": "'true'",
                    "substation_cleanliness": "'true'",
                    "equipment_level": "'true'",
                    "bumt_marks_sparks": "'false'",
                    "oxidation_corrosions": "'false'",
                    "dust_foreignDebris": "'true'",
                    "connectors_lugs": "'true'",
                    "bumt_heatingMarksOnCable": "'true'",
                    "urgent_issue": "'true'",
                    "urgent_issue_body": "'Null'",
                    "serious_issue": "'false'",
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": "> 40",
                    "rust_corrosion_deterioration": "10 - 20",
                    "paint_condition": "20 - 40",
                    "gaps_slots": "10 - 20",
                    "locks_hinges": "20 - 40",
                    "latching_mechanism": "> 40",
                    "cracks_damages": "20 - 40",
                    "gaps_unblockCableEntry": "10 - 20",
                    "galvanization_bolts_nuts_screws": "20 - 40",
                    "grounding_bounding": 'Null',
                    "access_obstructions": "10 - 20",
                    "numbering_dangerSigns_monogram": "20 - 40",
                    "maintenance_completed": "> 40",
                    "minorRepair_made": 'Null',
                    "latitude": 24.153975904580598,
                    "longitude": 47.33114535917431,
                    "last_check_at": "2022-02-11T18:58:34.750957",
                    "checked_by": "string",
                    "device": 5,
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.33808,
                    24.157623
                    ]
                },
                "properties": {
                    "id": 326,
                    "checked": 'true',
                    "image": "/media/minipillar/upload/imgs/IMG_1644598897515.jpg",
                    "code": "OR66",
                    "manuf_serial_number": "yy67",
                    "miniPillar_type": 'Null',
                    "subtype_cd": "t",
                    "substation_number": "66",
                    "feeder_number": "3",
                    "circuits_number": "2",
                    "used_circuits_number": "11",
                    "subMiniPilar": 'Null',
                    "manuf_code": "thh",
                    "manuf_year": "jja",
                    "created_at": "2022-02-11T15:38:47.630941",
                    "user": "admin",
                    "updated_at": "2022-02-11T19:02:10.546972",
                    "updated_by": 'Null',
                    "entrance_obstacles": "'true'",
                    "equipment_grounding": "'true'",
                    "rusted_earthing_connection": "'false'",
                    "availability_noDang_signsMono": "'true'",
                    "substation_cleanliness": "'false'",
                    "equipment_level": "'true'",
                    "bumt_marks_sparks": "'true'",
                    "oxidation_corrosions": "'true'",
                    "dust_foreignDebris": "'true'",
                    "connectors_lugs": "'false'",
                    "bumt_heatingMarksOnCable": "'true'",
                    "urgent_issue": "'true'",
                    "urgent_issue_body": "'Null'",
                    "serious_issue": "'false'",
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": "10 - 20",
                    "rust_corrosion_deterioration": "20 - 40",
                    "paint_condition": "> 40",
                    "gaps_slots": "10 - 20",
                    "locks_hinges": "20 - 40",
                    "latching_mechanism": "> 40",
                    "cracks_damages": "10 - 20",
                    "gaps_unblockCableEntry": "10 - 20",
                    "galvanization_bolts_nuts_screws": "> 40",
                    "grounding_bounding": 'Null',
                    "access_obstructions": "20 - 40",
                    "numbering_dangerSigns_monogram": "10 - 20",
                    "maintenance_completed": "> 40",
                    "minorRepair_made": 'Null',
                    "latitude": 24.157623370851688,
                    "longitude": 47.33808035316515,
                    "last_check_at": "2022-02-11T19:02:10.546972",
                    "checked_by": "string",
                    "device": 5,
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.337946,
                    24.159312
                    ]
                },
                "properties": {
                    "id": 322,
                    "checked": 'true',
                    "image": "/media/minipillar/upload/imgs/IMG_1644598996253.jpg",
                    "code": "OR88",
                    "manuf_serial_number": "H54a",
                    "miniPillar_type": 'Null',
                    "subtype_cd": "guru",
                    "substation_number": "22",
                    "feeder_number": "36",
                    "circuits_number": "66",
                    "used_circuits_number": "25",
                    "subMiniPilar": 'Null',
                    "manuf_code": "gg",
                    "manuf_year": "yy55",
                    "created_at": "2022-02-11T15:38:47.595117",
                    "user": "admin",
                    "updated_at": "2022-02-11T19:03:47.482662",
                    "updated_by": 'Null',
                    "entrance_obstacles": "'true'",
                    "equipment_grounding": "'false'",
                    "rusted_earthing_connection": "'false'",
                    "availability_noDang_signsMono": "'false'",
                    "substation_cleanliness": "'true'",
                    "equipment_level": "'true'",
                    "bumt_marks_sparks": "'false'",
                    "oxidation_corrosions": "'true'",
                    "dust_foreignDebris": "'true'",
                    "connectors_lugs": "'false'",
                    "bumt_heatingMarksOnCable": "'true'",
                    "urgent_issue": "'true'",
                    "urgent_issue_body": "'Null'",
                    "serious_issue": "'false'",
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": "10 - 20",
                    "rust_corrosion_deterioration": "20 - 40",
                    "paint_condition": "20 - 40",
                    "gaps_slots": "10 - 20",
                    "locks_hinges": "20 - 40",
                    "latching_mechanism": "> 40",
                    "cracks_damages": "20 - 40",
                    "gaps_unblockCableEntry": "10 - 20",
                    "galvanization_bolts_nuts_screws": "20 - 40",
                    "grounding_bounding": 'Null',
                    "access_obstructions": "> 40",
                    "numbering_dangerSigns_monogram": "10 - 20",
                    "maintenance_completed": "> 40",
                    "minorRepair_made": 'Null',
                    "latitude": 24.159311825602177,
                    "longitude": 47.33794560530359,
                    "last_check_at": "2022-02-11T19:03:47.482662",
                    "checked_by": "string",
                    "device": 5,
                    "created_by": 1
                }
                },
                {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                    47.336948,
                    24.158615
                    ]
                },
                "properties": {
                    "id": 325,
                    "checked": 'true',
                    "image": "/media/minipillar/upload/imgs/IMG_1644599090369.jpg",
                    "code": "OR65",
                    "manuf_serial_number": "y5h8",
                    "miniPillar_type": 'Null',
                    "subtype_cd": "gssa",
                    "substation_number": "25",
                    "feeder_number": "251",
                    "circuits_number": "25",
                    "used_circuits_number": "25",
                    "subMiniPilar": 'Null',
                    "manuf_code": "fcc5",
                    "manuf_year": "gf5h",
                    "created_at": "2022-02-11T15:38:47.621940",
                    "user": "admin",
                    "updated_at": "2022-02-11T19:05:18.809245",
                    "updated_by": 'Null',
                    "entrance_obstacles": "'false'",
                    "equipment_grounding": "'false'",
                    "rusted_earthing_connection": "'true'",
                    "availability_noDang_signsMono": "'false'",
                    "substation_cleanliness": "'true'",
                    "equipment_level": "'true'",
                    "bumt_marks_sparks": "'false'",
                    "oxidation_corrosions": "'true'",
                    "dust_foreignDebris": "'false'",
                    "connectors_lugs": "'true'",
                    "bumt_heatingMarksOnCable": "'false'",
                    "urgent_issue": "'true'",
                    "urgent_issue_body": "'Null'",
                    "serious_issue": "'false'",
                    "serious_issue_body": "'Null'",
                    "physicalCondition_dent_damages": "> 40",
                    "rust_corrosion_deterioration": "10 - 20",
                    "paint_condition": "> 40",
                    "gaps_slots": "> 40",
                    "locks_hinges": "10 - 20",
                    "latching_mechanism": "20 - 40",
                    "cracks_damages": "10 - 20",
                    "gaps_unblockCableEntry": "> 40",
                    "galvanization_bolts_nuts_screws": "20 - 40",
                    "grounding_bounding": 'Null',
                    "access_obstructions": "20 - 40",
                    "numbering_dangerSigns_monogram": "> 40",
                    "maintenance_completed": "10 - 20",
                    "minorRepair_made": 'Null',
                    "latitude": 24.15861513597105,
                    "longitude": 47.33694847551266,
                    "last_check_at": "2022-02-11T19:05:18.809245",
                    "checked_by": "string",
                    "device": 5,
                    "created_by": 1
                }
                }
            ]
            }
    gis = GIS()
    gis.json_to_file(json_object)
    
    
if __name__ == "__main__":
    main()