# Generated by Django 3.0.6 on 2022-01-06 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_minipillarshapefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniPillarJsonFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('jsonfile', models.FileField(upload_to='temp_json/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'minipillar_jsonfile',
            },
        ),
        migrations.DeleteModel(
            name='MiniPillarShapefile',
        ),
    ]
