# Generated by Django 3.0.6 on 2022-01-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220106_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minipillarjsonfile',
            name='jsonfile',
        ),
        migrations.AddField(
            model_name='minipillarjsonfile',
            name='json_object',
            field=models.TextField(default=1, max_length=4000),
            preserve_default=False,
        ),
    ]
