# Generated by Django 3.0.6 on 2022-01-06 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_minipillarjsonfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipillarjsonfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
