# Generated by Django 3.0.6 on 2022-01-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_minipillarjsonfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipillarjsonfile',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
