# Generated by Django 3.0.6 on 2022-01-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_minipillarjsonfile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minipillar',
            name='access_obstructions',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='availability_noDang_signsMono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='bumt_heatingMarksOnCable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='bumt_marks_sparks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='circuits_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='connectors_lugs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='cracks_damages',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='dust_foreignDebris',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='entrance_obstacles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='equipment_grounding',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='equipment_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='feeder_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='galvanization_bolts_nuts_screws',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='gaps_slots',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='gaps_unblockCableEntry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='grounding_bounding',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='latching_mechanism',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='locks_hinges',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='maintenance_completed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='manuf_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='manuf_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='manuf_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='miniPillar_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='minorRepair_made',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='numbering_dangerSigns_monogram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='oxidation_corrosions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='paint_condition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='physicalCondition_dent_damages',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='rust_corrosion_deterioration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='rusted_earthing_connection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='serious_issue_body',
            field=models.TextField(blank=True, default='Null', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='subMiniPilar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='substation_cleanliness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='substation_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='subtype_cd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='urgent_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='urgent_issue_body',
            field=models.TextField(blank=True, default='Null', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='minipillar',
            name='used_circuits_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
