# Generated by Django 3.0.6 on 2022-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220106_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipillar',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
