# Generated by Django 3.0.6 on 2022-01-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_minipillar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minipillar',
            name='serious_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
