# Generated by Django 3.0.6 on 2022-01-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220107_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minipillar',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device'),
        ),
    ]
