# Generated by Django 3.0.6 on 2022-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220109_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minipillar',
            name='image',
            field=models.FileField(default='static/upload/imgs/no_img.png', upload_to='static/upload/imgs/'),
        ),
    ]
