# Generated by Django 3.0.6 on 2022-01-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220111_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minipillar',
            old_name='image',
            new_name='filename',
        ),
    ]
