# Generated by Django 3.0.6 on 2022-01-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_minipillar_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipillar',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
