# Generated by Django 3.0.6 on 2022-01-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_minipillar_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minipillar',
            name='checked',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
