# Generated by Django 3.0.6 on 2022-01-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220117_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minipillar',
            name='checked',
        ),
    ]
