# Generated by Django 3.0.6 on 2022-01-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220117_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minipillar',
            name='image',
        ),
    ]
