# Generated by Django 3.0.6 on 2022-01-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220117_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minipillar',
            name='image',
            field=models.ImageField(default='media/minipillar/upload/imgs/no_img.png', upload_to='static/upload/imgs/'),
        ),
    ]
