# Generated by Django 3.0.6 on 2022-01-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220125_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minipillar',
            name='image',
        ),
    ]
