# Generated by Django 3.0.6 on 2022-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_minipillar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipillar',
            name='image',
            field=models.ImageField(default='media/minipillar/upload/imgs/no_img.png', upload_to='static/upload/imgs/'),
        ),
    ]
