# Generated by Django 3.0.6 on 2022-01-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_minipillar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minipillar',
            name='image',
        ),
    ]
