# Generated by Django 3.0.6 on 2022-02-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_minipillar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='group',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
