# Generated by Django 3.0.6 on 2022-02-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20220205_0929'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='minipillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.MiniPillar'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FilePathField(),
        ),
        migrations.AlterModelTable(
            name='reportfile',
            table='minipillar_report',
        ),
    ]
