# Generated by Django 3.0.6 on 2022-04-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportFile',
        ),
    ]
