# Generated by Django 3.0.6 on 2022-02-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220211_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportFile',
        ),
    ]
