# Generated by Django 3.0.6 on 2022-04-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_reportfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinipillarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temp/file/')),
            ],
        ),
    ]
