# Generated by Django 3.0.6 on 2022-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_minipillarfile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='minipillarfile',
            table='minipillarfile',
        ),
    ]
